### PR TITLE
Improve formatting and data in setup.py

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Fixes: author (maintainer) + email, link.

Salvaged from #28 .

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by VladimirSlavik** [comment]
Rebased to resolve conflict in version number.

**Comment by VladimirSlavik** [comment]
Bump?

**Review by poncovka — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks a lot for the cleanup! :)

**Pull request merged**
